version: '3.8'

services:
  postgresql:
    build: ./docker/pgfiledump/
    container_name: postgres_tuning
    environment:
      POSTGRES_DB: tuning
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./workspace:/workspace
  mysql:
    image: mysql:8.0
    container_name: mysql_tuning
    environment:
      MYSQL_DATABASE: tuning
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  postgres_data:
  mysql_data: